Add packaging functionality
ondewo/ondewo-monitoring pull request #1
Opened 2021-11-23 08:48 UTC by gaborod16

Integration of packaging capabilities for portability

2021-11-23 11:14 UTC, teddius requested changes

2021-11-23 11:14 UTC, teddius commented on docker-compose.published_dependencies.yml
> +      - 9090
Add port into environment file

2021-11-23 11:14 UTC, teddius commented on docker-compose.published_dependencies.yml
> +      - 9093
Add port into environment file

2021-11-23 11:14 UTC, teddius commented on docker-compose.published_dependencies.yml
> +      - 9100
Add port into environment file

2021-11-23 11:14 UTC, teddius commented on docker-compose.published_dependencies.yml
> +      - 8080
Add port into environment file

2021-11-23 11:14 UTC, teddius commented on docker-compose.published_dependencies.yml
> +      - 3000
Add port into environment file

2021-11-23 11:14 UTC, teddius commented on docker-compose.published_dependencies.yml
> +      - 9091
Add port into environment file

2021-11-23 11:14 UTC, teddius commented on docker-compose.published_dependencies.yml
> +    ports:
Add ports into environment file

2021-11-23 11:14 UTC, teddius commented on packaging/example.env
> +# Packaging
Add ports into this environment file so it is possible to configure the ports from the environment file

2021-11-29 11:48 UTC, MohamedYaman approved these changes
Good job Gabe!

2021-11-29 11:51 UTC, merged